### ISSUE TITLE
爬虫下载的图片经过压缩，如何下载原图呢

### ISSUE THREAD

**Issue by abk-buding** [eesxy/Dmzj_backup#1]
请求的图片url正确，但最后保存的图片和直接用URL下载不一致，有被处理压缩。
如何得到原图呢？

顺便感谢作者，对小白来说很方便

**Comment by eesxy** [comment]
很抱歉没有及时回复你，图片被压缩的问题经检查发现是`ImagePipeline`会通过调用PIL的`save`方法保存图片，这一方法默认会对图像进行压缩，现已改用`FilesPipeline`。请升级到v2.0.4版本后再次测试，对应commit`6e24972988da70a77dd91fa6cda4c46754de6c40`
